apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-kb-backend
  namespace: confluence-kb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: confluence-kb-backend
  template:
    metadata:
      labels:
        app: confluence-kb-backend
    spec:
      containers:
      - name: backend
        image: <your-acr-name>.azurecr.io/confluence-kb-backend:<tag>
        envFrom:
        - configMapRef:
            name: confluence-kb-config
        - secretRef:
            name: confluence-kb-secrets
        ports:
        - containerPort: 8000
        command: ["uvicorn"]  # This overrides Dockerfile CMD
        args: ["backend:app", "--host", "0.0.0.0", "--port", "8000"]  # Arguments to 'uvicorn'
        resources
