apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: confluence-chat
data:
  # The space key to restrict crawling to (hard-coded)
  SPACE_KEY: "ENG"                # <--- replace with your required space key
  CONFLUENCE_BASE_URL: "http://confluence.internal.company"  # base host, no trailing slash
  USE_BLOB: "false"               # "true" if you will enable blob backup in ingestion worker
  CHUNK_SIZE: "800"               # approx tokens/characters per chunk
  CHUNK_OVERLAP: "150"
  SCRAPE_START_PATH: "/display/ENG"  # starting path to crawl; must include SPACE_KEY
  SCRAPE_MAX_PAGES: "2000"         # safety limit for the crawler