apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: confluence-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: <YOUR_REGISTRY>/confluence-streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: "http://backend.confluence-chat.svc.cluster.local:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: confluence-chat
spec:
  selector:
    app: streamlit
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
  type: ClusterIP
