apiVersion: batch/v1
kind: CronJob
metadata:
  name: confluence-ingest
  namespace: confluence-chat
spec:
  schedule: "*/30 * * * *"   # every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ingester
            image: <YOUR_REGISTRY>/confluence-ingest:latest
            envFrom:
            - secretRef:
                name: creds
            - configMapRef:
                name: app-config
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1"
                memory: "2Gi"
            # Use an emptyDir or PVC if you want to persist a local sqlite checkpoint
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
          - name: tmp
            emptyDir: {}
