jobs:
  create_aks_cluster:
    job_name: "Create-AKS-Cluster"
    job_path: "JobsFolder/Create-AKS-Cluster"
    jenkins_url: "http://jenkins.local/job/JobsFolder/job/Create-AKS-Cluster/buildWithParameters"
    documentation: "https://learn.microsoft.com/en-us/azure/aks/"
    parameters:
      - name: cluster_name
        prompt: "Enter AKS Cluster Name"
      - name: resource_group
        prompt: "Enter Resource Group Name"
      - name: location
        prompt: "Enter Azure Location"

  create_namespace:
    job_name: "Create-Namespace"
    job_path: "JobsFolder/Create-Namespace"
    jenkins_url: "http://jenkins.local/job/JobsFolder/job/Create-Namespace/buildWithParameters"
    documentation: "https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
    parameters:
      - name: cluster_name
        prompt: "Enter Cluster Name"
      - name: namespace
        prompt: "Enter Namespace Name"

  create_rolebinding:
    job_name: "Create-RoleBinding"
    job_path: "JobsFolder/Create-RoleBinding"
    jenkins_url: "http://jenkins.local/job/JobsFolder/job/Create-RoleBinding/buildWithParameters"
    documentation: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/"
    parameters:
      - name: cluster_name
        prompt: "Enter Cluster Name"
      - name: namespace
        prompt: "Enter Namespace"
      - name: user
        prompt: "Enter User Name"
